[workspace]
  members = ["crates/app", "crates/privd", "crates/common"]
  resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.20", features = ["derive"] }
ctrlc = "3.4.5"
drm = "0.14.1"
drm-sys = "0.8.0"
env_logger = "0.11.9"
eyre = "0.6.12"
gl = "0.14.0"
khronos-egl = { version = "6.0.0", features = ["static"] }
libc = "0.2.182"
log = "0.4.29"
serde = "1.0.228"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
bincode = "1.3.3"
nix = { version = "0.29.0", features = ["socket", "uio"] }
