[package]
name = "framepipe-privd"
version.workspace = true
edition = "2024"

[dependencies]
common = { path = "../common" }
drm = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
nix = { workspace = true }
thiserror = { workspace = true }
eyre = { workspace = true }
libc = { workspace = true }
