name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - dev

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: bash .github/scripts/install-system-deps.sh ubuntu

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo check --all-targets
  

  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: bash .github/scripts/install-system-deps.sh ubuntu

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo clippy --all-targets -- -D warnings

  arch-ci:
    runs-on: ubuntu-24.04
    container:
      image: archlinux:base-devel

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: bash .github/scripts/install-system-deps.sh arch

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --all-targets